stages:
  auth:
    cmd: calkit xenv -n main -- python scripts/auth.py
    deps:
      - scripts/auth.py
      - requirements.txt
    outs:
      - .env:
          cache: false
          persist: true
    always_changed: true
  # Months is a dynamic parameter, updated by Calkit before running the pipeline
  get-data:
    foreach: ${months}
    do:
      cmd: >
        calkit xenv -n main --
        python scripts/get-data.py --year ${item.year} --month ${item.month}
      deps:
        - requirements.txt
        - scripts/get-data.py
      outs:
        - data/activities/year=${item.year}/month=${item.month}/data.csv:
            cache: false
        - data/timeseries/year=${item.year}/month=${item.month}
