stages:
  get-data:
    cmd: calkit xenv -n main -- python scripts/get-data.py
    deps:
      - scripts/get-data.py
      - pypkg/strava.py
    outs:
      - data/activities:
          cache: false
          persist: true
      - data/timeseries:
          persist: true
    always_changed: true
  plot-weekly-dists:
    desc: Plot weekly power and heart rate distributions.
    cmd: calkit xenv -n main -- python scripts/plot-weekly-dists.py
    deps:
      - data/timeseries
      - data/activities
      - scripts/plot-weekly-dists.py
      - pypkg/plot.py
    outs:
      - figures/weekly-dists-24-weeks.json:
          cache: false
      - figures/dists-latest-week.json:
          cache: false
  plot-weekly-energy:
    cmd: calkit xenv -n main -- python scripts/plot-weekly-energy.py
    deps:
      - data/activities
      - scripts/plot-weekly-energy.py
    outs:
      - figures/weekly-energy.json:
          cache: false
  calc-latest-timestamp:
    cmd: calkit calc latest_timestamp
    desc: >
      This stage was automatically generated from the 'latest_timestamp'
      calculation.
    deps:
      - data/activities # TODO: Auto-detect this?
      - pyproject.toml # TODO: Auto-detect this
      - .calkit/calculations/latest_timestamp.yaml
    outs:
      - .calkit/calculations/outputs/latest_timestamp.yaml
