stages:
  auth:
    cmd: calkit xenv -n main -- python scripts/auth.py
    deps:
      - scripts/auth.py
      - requirements.txt
    outs:
      - .env:
          cache: false
          persist: true
    always_changed: true
  # Before the pipeline is executed, we will update `today` in params.yaml to
  # ensure this is rerun when we turn over to a new day
  get-data:
    cmd: calkit xenv -n main -- python scripts/get-data.py --end ${today}
    deps:
      - requirements.txt
      - scripts/get-data.py
    outs:
      - data/activities.csv
      - data/timeseries
