stages:
  auth:
    cmd: calkit xenv -n main -- python scripts/auth.py
    deps:
      - scripts/auth.py
      - requirements.txt
    outs:
      - .env:
          cache: false
          persist: true
    always_changed: true
  get-data:
    cmd: calkit xenv -n main -- python scripts/get-data.py
    deps:
      - requirements.txt
      - scripts/get-data.py
    outs:
      - data/activities:
          cache: false
          persist: true
      - data/timeseries:
          persist: true
