stages:
  auth:
    cmd: calkit xenv -n main -- python scripts/auth.py
    deps:
      - scripts/auth.py
      - requirements.txt
    outs:
      - .env:
          cache: false
          persist: true
    always_changed: true
  # This script is smart enough to not do duplicate work, so consider it
  # always changed
  get-data:
    cmd: calkit xenv -n main -- python scripts/get-data.py
    deps:
      - requirements.txt
      - scripts/get-data.py
    outs:
      - data/activities.csv:
          cache: false
          persist: true
      - data/timeseries:
          persist: true
    always_changed: true
