stages:
  auth:
    cmd: calkit xenv -n main -- python scripts/auth.py
    deps:
      - scripts/auth.py
      - requirements.txt
    outs:
      - .env:
          cache: false
          persist: true
    always_changed: true
  get-activities:
    foreach: ${dates}
    do:
      cmd: >
        calkit xenv -n main --
        python scripts/get-data.py --date ${item}
      deps:
        - requirements.txt
        - scripts/get-data.py
      outs:
        - data/activities/${item}:
            cache: false
  get-timeseries:
    foreach: ${activity_ids}
    do:
      cmd: >
        calkit xenv -n main --
        python scripts/get-ts-data.py --activity-id ${item}
      deps:
        - scripts/get-ts-data.py
      outs:
        - data/timeseries/activity_id=${item}/data.parquet
