stages:
  auth:
    cmd: calkit xenv -n main -- python scripts/auth.py
    deps:
      - scripts/auth.py
      - requirements.txt
    outs:
      - .env:
          cache: false
          persist: true
    always_changed: true
  get-data:
    cmd: calkit xenv -n main -- python scripts/get-data.py
    deps:
      - requirements.txt
      - scripts/get-data.py
    outs:
      - data/activities:
          cache: false
          persist: true
      - data/timeseries:
          persist: true
    always_changed: true
  plot-current-week-dist:
    desc: Plot the current week's power and heart rate distributions.
    cmd: >
      calkit xenv -n main --
      python scripts/plot-dists.py --this-week
    deps:
      - data/timeseries
      - data/activities
      - scripts/plot-dists.py
    outs:
      - figures/dists-this-week.json
    meta:
      calkit:
        type: figure
        title: This week's distributions
        description: Power and heart rate distributions from the current week.
  invalidate-weekly-dists:
    cmd: calkit queue --name weekly-dist-plots resubmit --all
    deps:
      - scripts/plot-dists.py
  plot-weekly-dists:
    desc: Plot weekly power and heart rate distributions.
    cmd: calkit queue consume weekly-dist-plots
    deps:
      - .calkit/queues/weekly-dist-plots.yaml
    outs:
      - figures/weekly-dists:
          persist: true
